server:
  port: 80    # порт на котором работает приложение
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true

spring:
  jmx:
    enabled: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLiteDialect    # диалект sql для подключения hibernate к базе данных
  datasource:
    url: jdbc:sqlite:Backend/src/main/resources/webService.db    # путь до базы данных
    driver-class-name: org.sqlite.JDBC    # класс драйвера для подключения к базе данных
  flyway:
    baseline-on-migrate: true    # применять схемы миграции, если они не применены
    outOfOrder: true    # позволяет добавлять схемы миграции с номером не по-порядку
    schemas:    # схема, в которую flyway будет делать миграцию
  mvc:
    throw-exception-if-no-handler-found: true




