server:
  port: 443    # порт на котором работает приложение
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  ssl:
    key-store-type: JKS
    key-store: classpath:keystore.jks
    key-password: changeit
    key-alias: react-web-service
    enabled: true
    protocol: TLS
    client-auth: want

spring:
  jmx:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLiteDialect    # диалект sql для подключения hibernate к базе данных
  datasource:
    url: jdbc:sqlite:Backend/src/main/resources/webService.db    # путь до базы данных
    driver-class-name: org.sqlite.JDBC    # класс драйвера для подключения к базе данных
  flyway:
    baseline-on-migrate: true    # применять схемы миграции, если они не применены
    outOfOrder: true    # позволяет добавлять схемы миграции с номером не по-порядку
    schemas:    # схема, в которую flyway будет делать миграцию
  mvc:
    throw-exception-if-no-handler-found: true

jwt:
  validityinmilliseconds: 60000000
  secretkey: atagan
  cookie.name: JWTToken




