server:
  port: 80 # порт на котором работает приложение

spring:
  datasource:
    url: jdbc:sqlite:Backend/src/main/resources/webService.db # путь до базы данных
    driver-class-name: org.sqlite.JDBC # класс драйвера для базы данных


