
spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLiteDialect    # диалект sql для подключения hibernate к базе данных
  datasource:
    url: jdbc:sqlite:Backend/Core/src/main/resources/webService.db    # путь до базы данных
    driver-class-name: org.sqlite.JDBC    # класс драйвера для подключения к базе данных




